

import {
    Armchair,
    Baby,
    BarChart2,
    Bath,
    BedDouble,
    Beef,
    Bike,
    Bone,
    BookOpen,
    Briefcase,
    Brush,
    BusFront,
    Calendar,
    CalendarClock,
    CalendarDays,
    Car,
    CarFront,
    Carrot,
    Cat,
    CheckCircle2,
    CheckSquare,
    ChefHat,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    Cigarette,
    Clapperboard,
    Cloud,
    Coins,
    Cookie,
    CreditCard,
    Croissant,
    Dog,
    DownloadCloud,
    Droplets,
    Dumbbell,
    Edit,
    Expand,
    FileText,
    Film,
    Fish,
    Filter,
    FlaskConical,
    Fuel,
    Gamepad2,
    Gauge,
    Gift,
    Globe,
    GraduationCap,
    GripVertical,
    Hammer,
    HardHat,
    Hash,
    Headphones,
    HeartHandshake,
    HeartPulse,
    History,
    Home,
    Info,
    KeyRound,
    Landmark,
    LayoutDashboard,
    LayoutGrid,
    Leaf,
    Link,
    List,
    Loader2,
    LogIn,
    LogOut,
    Luggage,
    MoreHorizontal,
    MousePointerClick,
    Music,
    Navigation,
    Package,
    Paintbrush,
    PartyPopper,
    PawPrint,
    PiggyBank,
    Pill,
    Pizza,
    Plane,
    Plus,
    RefreshCw,
    Repeat,
    Router,
    Save,
    Scale,
    Scissors,
    School,
    Search,
    Settings,
    Sheet,
    ShieldCheck,
    Shirt,
    ShoppingBasket,
    ShoppingBag,
    ShowerHead,
    ShoppingCart,
    Shrink,
    Signal,
    SlidersHorizontal,
    Smartphone,
    Sofa,
    Sparkles,
    Sprout,
    SprayCan,
    Square,
    Stethoscope,
    Store,
    Tag,
    Tags,
    Target,
    Ticket,
    ToyBrick,
    TrainFront,
    Trash2,
    TrendingDown,
    Tv,
    User,
    Users,
    UtensilsCrossed,
    Wallet,
    Wifi,
    Wrench,
    X,
    Zap,
} from 'lucide-react';
import type { LucideProps } from 'lucide-react';
import type { FC } from 'react';

export const iconMap: { [key: string]: FC<LucideProps> } = {
    Armchair, Baby, BarChart2, Bath, BedDouble, Beef, Bike, Bone, BookOpen, Briefcase, Brush, BusFront, Calendar, CalendarClock,
    CalendarDays, Car, CarFront, Carrot, Cat, CheckCircle2, CheckSquare, ChefHat, ChevronDown, ChevronLeft, ChevronRight,
    ChevronUp, Cigarette, Clapperboard, Cloud, Coins, Cookie, CreditCard, Croissant, Dog, DownloadCloud, Droplets, Dumbbell,
    Edit, Expand, FileText, Film, Fish, Filter, FlaskConical, Fuel, Gamepad2, Gauge, Gift, Globe, GraduationCap, GripVertical, Hammer, HardHat,
    Hash, Headphones, HeartHandshake, HeartPulse, History, Home, Info, KeyRound, Landmark, LayoutDashboard, LayoutGrid, Leaf, Link,
    List, Loader2, LogIn, LogOut, Luggage, MoreHorizontal, MousePointerClick, Music, Navigation, Package, Paintbrush, PartyPopper, PawPrint,
    PiggyBank, Pill, Pizza, Plane, Plus, RefreshCw, Repeat, Router, Save, Scale, Scissors, School, Search, Settings, Sheet, ShieldCheck,
    Shirt, ShoppingBasket, ShoppingBag, ShowerHead, ShoppingCart, Shrink, Signal, SlidersHorizontal, Smartphone, Sofa, Sparkles, Sprout,
    SprayCan, Square, Stethoscope, Store, Tag, Tags, Target, Ticket, ToyBrick, TrainFront, Trash2, TrendingDown, Tv, User, Users,
    UtensilsCrossed, Wallet, Wifi, Wrench, X, Zap,
};

export {
    Armchair, Baby, BarChart2, Bath, BedDouble, Beef, Bike, Bone, BookOpen, Briefcase, Brush, BusFront, Calendar, CalendarClock,
    CalendarDays, Car, CarFront, Carrot, Cat, CheckCircle2, CheckSquare, ChefHat, ChevronDown, ChevronLeft, ChevronRight,
    ChevronUp, Cigarette, Clapperboard, Cloud, Coins, Cookie, CreditCard, Croissant, Dog, DownloadCloud, Droplets, Dumbbell,
    Edit, Expand, FileText, Film, Fish, Filter, FlaskConical, Fuel, Gamepad2, Gauge, Gift, Globe, GraduationCap, GripVertical, Hammer, HardHat,
    Hash, Headphones, HeartHandshake, HeartPulse, History, Home, Info, KeyRound, Landmark, LayoutDashboard, LayoutGrid, Leaf, Link,
    List, Loader2, LogIn, LogOut, Luggage, MoreHorizontal, MousePointerClick, Music, Navigation, Package, Paintbrush, PartyPopper, PawPrint,
    PiggyBank, Pill, Pizza, Plane, Plus, RefreshCw, Repeat, Router, Save, Scale, Scissors, School, Search, Settings, Sheet, ShieldCheck,
    Shirt, ShoppingBasket, ShoppingBag, ShowerHead, ShoppingCart, Shrink, Signal, SlidersHorizontal, Smartphone, Sofa, Sparkles, Sprout,
    SprayCan, Square, Stethoscope, Store, Tag, Tags, Target, Ticket, ToyBrick, TrainFront, Trash2, TrendingDown, Tv, User, Users,
    UtensilsCrossed, Wallet, Wifi, Wrench, X, Zap,
};

/**
 * Retrieves an icon component from the iconMap.
 * Falls back to a default icon if the name is not found.
 * @param iconName The name of the icon to retrieve.
 * @returns A React component for the icon.
 */
export const getIconComponent = (iconName?: string): FC<LucideProps> => {
    if (iconName && iconMap[iconName]) {
        return iconMap[iconName];
    }
    return iconMap.MoreHorizontal;
};