
import {
    Baby,
    BarChart2,
    Beef,
    Bone,
    BookOpen,
    Briefcase,
    BusFront,
    Calendar,
    CalendarDays,
    Car,
    Carrot,
    CheckCircle2,
    CheckSquare,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    Cigarette,
    Cloud,
    Coins,
    CreditCard,
    Croissant,
    DownloadCloud,
    Dumbbell,
    Edit,
    Expand,
    Film,
    Fish,
    Filter,
    FlaskConical,
    Fuel,
    Gamepad2,
    Gift,
    Globe,
    GraduationCap,
    GripVertical,
    Hash,
    HeartHandshake,
    HeartPulse,
    History,
    Home,
    Info,
    KeyRound,
    Landmark,
    LayoutDashboard,
    LayoutGrid,
    Leaf,
    Link,
    List,
    Loader2,
    LogIn,
    LogOut,
    MoreHorizontal,
    Package,
    Paintbrush,
    PawPrint,
    PiggyBank,
    Pill,
    Plane,
    Plus,
    RefreshCw,
    Repeat,
    Router,
    Save,
    Scale,
    Scissors,
    Search,
    Settings,
    Sheet,
    ShieldCheck,
    Shirt,
    ShowerHead,
    ShoppingCart,
    Shrink,
    Signal,
    SlidersHorizontal,
    Sofa,
    Sparkles,
    SprayCan,
    Square,
    Stethoscope,
    Store,
    Tag,
    Tags,
    Target,
    Ticket,
    TrainFront,
    Trash2,
    TrendingDown,
    Tv,
    User,
    Users,
    UtensilsCrossed,
    Wallet,
    Wrench,
    X,
    Zap,
} from 'lucide-react';
import type { LucideProps } from 'lucide-react';
import type { FC } from 'react';

export const iconMap: { [key: string]: FC<LucideProps> } = {
    Baby, BarChart2, Beef, Bone, BookOpen, Briefcase, BusFront, Calendar, CalendarDays,
    Car, Carrot, CheckCircle2, CheckSquare, ChevronDown, ChevronLeft, ChevronRight,
    ChevronUp, Cigarette, Cloud, Coins, CreditCard, Croissant, DownloadCloud, Dumbbell,
    Edit, Expand, Film, Fish, Filter, FlaskConical, Fuel, Gamepad2, Gift, Globe,
    GraduationCap, GripVertical, Hash, HeartHandshake, HeartPulse, History, Home,
    Info, KeyRound, Landmark, LayoutDashboard, LayoutGrid, Leaf, Link, List, Loader2,
    LogIn, LogOut, MoreHorizontal, Package, Paintbrush, PawPrint, PiggyBank, Pill,
    Plane, Plus, RefreshCw, Repeat, Router, Save, Scale, Scissors, Search, Settings,
    Sheet, ShieldCheck, Shirt, ShowerHead, ShoppingCart, Shrink, Signal,
    SlidersHorizontal, Sofa, Sparkles, SprayCan, Square, Stethoscope, Store, Tag,
    Tags, Target, Ticket, TrainFront, Trash2, TrendingDown, Tv, User, Users,
    UtensilsCrossed, Wallet, Wrench, X, Zap,
};

export {
    Baby, BarChart2, Beef, Bone, BookOpen, Briefcase, BusFront, Calendar, CalendarDays,
    Car, Carrot, CheckCircle2, CheckSquare, ChevronDown, ChevronLeft, ChevronRight,
    ChevronUp, Cigarette, Cloud, Coins, CreditCard, Croissant, DownloadCloud, Dumbbell,
    Edit, Expand, Film, Fish, Filter, FlaskConical, Fuel, Gamepad2, Gift, Globe,
    GraduationCap, GripVertical, Hash, HeartHandshake, HeartPulse, History, Home,
    Info, KeyRound, Landmark, LayoutDashboard, LayoutGrid, Leaf, Link, List, Loader2,
    LogIn, LogOut, MoreHorizontal, Package, Paintbrush, PawPrint, PiggyBank, Pill,
    Plane, Plus, RefreshCw, Repeat, Router, Save, Scale, Scissors, Search, Settings,
    Sheet, ShieldCheck, Shirt, ShowerHead, ShoppingCart, Shrink, Signal,
    SlidersHorizontal, Sofa, Sparkles, SprayCan, Square, Stethoscope, Store, Tag,
    Tags, Target, Ticket, TrainFront, Trash2, TrendingDown, Tv, User, Users,
    UtensilsCrossed, Wallet, Wrench, X, Zap,
};

/**
 * Retrieves an icon component from the iconMap.
 * Falls back to a default icon if the name is not found.
 * @param iconName The name of the icon to retrieve.
 * @returns A React component for the icon.
 */
export const getIconComponent = (iconName?: string): FC<LucideProps> => {
    if (iconName && iconMap[iconName]) {
        return iconMap[iconName];
    }
    return iconMap.MoreHorizontal;
};
