export const iconGroups = {
  'Essen & Trinken': ['Apple', 'Banana', 'Bean', 'Beef', 'Beer', 'BottleWine', 'Candy', 'CandyCane', 'Carrot', 'ChefHat', 'Cherry', 'Citrus', 'Coffee', 'Cookie', 'Croissant', 'CupSoda', 'Donut', 'Fish', 'GlassWater', 'IceCream', 'IceCream2', 'IceCreamBowl', 'Lollipop', 'Milk', 'Nut', 'Pizza', 'Salad', 'Sandwich', 'Shrimp', 'Soup', 'Utensils', 'UtensilsCrossed', 'Wheat', 'Wine'],
  'Haushalt & Wohnen': ['Armchair', 'Bath', 'BedDouble', 'Book', 'BookOpen', 'Boxes', 'BrickWall', 'Brush', 'Home', 'KeyRound', 'Lamp', 'Paintbrush', 'Palette', 'Router', 'Save', 'Scissors', 'Shovel', 'Sofa', 'ShowerHead', 'SprayCan', 'Toilet', 'Wrench'],
  'Transport & Mobilität': ['Anchor', 'Backpack', 'BaggageClaim', 'Bike', 'Bus', 'BusFront', 'Car', 'CarFront', 'CarTaxiFront', 'Fuel', 'Luggage', 'Navigation', 'Plane', 'Rocket', 'Ship', 'Tractor', 'TrainFront', 'TrainFrontTunnel', 'TrainTrack', 'TramFront', 'Truck'],
  'Freizeit & Hobbies': ['Atom', 'Award', 'Binoculars', 'Clapperboard', 'Dice6', 'Dribbble', 'Drum', 'FerrisWheel', 'Film', 'Gamepad2', 'Ghost', 'Gift', 'HatGlasses', 'Headphones', 'Kayak', 'MicVocal', 'Music', 'Music4', 'PartyPopper', 'Puzzle', 'RollerCoaster', 'Tablet', 'TabletSmartphone', 'Telescope', 'Tent', 'TentTree', 'Theater', 'Ticket', 'ToyBrick', 'Tv', 'Tv2', 'TvMinimalPlay', 'Twitch', 'Twitter', 'Video', 'Videotape', 'Volleyball', 'Youtube', 'VenetianMask'],
  'Shopping & Finanzen': ['Bitcoin', 'Coins', 'CreditCard', 'Gem', 'HandCoins', 'PiggyBank', 'ShoppingBag', 'ShoppingBasket', 'ShoppingCart', 'Store', 'Wallet', 'Tags', 'Stamp'],
  'Gesundheit & Körper': ['Baby', 'BicepsFlexed', 'Bone', 'Brain', 'Dumbbell', 'Ear', 'Glasses', 'HandHeart', 'HeartHandshake', 'HeartPulse', 'Hospital', 'Pill', 'Stethoscope', 'Vegan', 'Sprout'],
  'Arbeit & Bildung': ['Briefcase', 'BookA', 'BookImage', 'Drill', 'FileText', 'GraduationCap', 'Hammer', 'HardHat', 'Landmark', 'PocketKnife', 'School', 'University'],
  'Tiere & Natur': ['Bird', 'Cat', 'Clover', 'Cloud', 'Dog', 'Droplet', 'Droplets', 'Feather', 'Flame', 'Leaf', 'Moon', 'Panda', 'PawPrint', 'Rabbit', 'Sparkles', 'Squirrel', 'TreePalm', 'Trees', 'Waves'],
  'Symbole & Sonstiges': ['Antenna', 'AtSign', 'BarChart2', 'Bomb', 'BookHeart', 'Bubbles', 'Calendar', 'CalendarClock', 'CalendarDays', 'Camera', 'CheckCircle2', 'CheckSquare', 'ChevronDown', 'ChevronLeft', 'ChevronRight', 'ChevronUp', 'Church', 'Cigarette', 'Crown', 'DownloadCloud', 'Edit', 'Expand', 'Eye', 'EyeClosed', 'EyeOff', 'Filter', 'Flashlight', 'FlaskConical', 'FlaskRound', 'Gauge', 'Globe', 'GripVertical', 'HandMetal', 'Hash', 'History', 'Info', 'LayoutDashboard', 'LayoutGrid', 'Lightbulb', 'Link', 'List', 'Loader2', 'Lock', 'LockOpen', 'LogIn', 'LogOut', 'Minus', 'MoreHorizontal', 'Mouse', 'MousePointerClick', 'Package', 'Plus', 'PlusCircle', 'RefreshCcw', 'RefreshCw', 'Repeat', 'Ribbon', 'Scale', 'Search', 'Settings', 'ShieldCheck', 'Shirt', 'Shrink', 'Signal', 'Siren', 'Skull', 'SlidersHorizontal', 'Smartphone', 'Square', 'Star', 'Tag', 'Target', 'ToggleLeft', 'ToggleRight', 'Trash2', 'TrendingDown', 'Umbrella', 'Undo2', 'User', 'Users', 'Watch', 'Wifi', 'X', 'Zap', 'ArrowLeftRight', 'ArrowUpDown', 'Upload'],
};
