import {
  Anchor, Antenna, Apple, Armchair, AtSign, Atom, Award, Axe, Baby,
  Backpack, BaggageClaim, Banana, BarChart2, Bath, Bean, BedDouble, Beef, Beer,
  BicepsFlexed, Bike, Binoculars, Bird, Bitcoin, Bomb, Bone, Book, BookA,
  BookHeart, BookImage, BookOpen, BottleWine, Boxes, Brain, Briefcase, BrickWall,
  Brush, Bubbles, Bus, BusFront, Calendar, CalendarClock, CalendarDays, Candy,
  CandyCane, Car, CarFront, CarTaxiFront, Carrot, Cat, CheckCircle2, CheckSquare,
  ChefHat, Cherry, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, Church,
  Cigarette, Citrus, Clapperboard, Cloud, Clover, Coffee, Coins, Cookie,
  CreditCard, Croissant, Crown, CupSoda, Dice6, Dog, Donut, DownloadCloud,
  Dribbble, Drill, Droplet, Droplets, Drum, Dumbbell, Ear, Edit, Expand, Eye,
  EyeClosed, EyeOff, Feather, FerrisWheel, FileText, Film, Fish, Filter, Flame,
  Flashlight, FlaskConical, FlaskRound, Fuel, Gamepad2, Gauge, Gem, Ghost, Gift,
  GlassWater, Glasses, Globe, GraduationCap, GripVertical, Hammer, HandCoins,
  HandHeart, HandMetal, HardHat, Hash, HatGlasses, Headphones, HeartHandshake,
  HeartPulse, History, Home, Hospital, IceCream, IceCream2, IceCreamBowl, Info,
  Kayak, KeyRound, Lamp, Landmark, LayoutDashboard, LayoutGrid, Leaf, Lightbulb,
  Link, List, Loader2, LogIn, LogOut, Lollipop, Luggage, MicVocal, Milk, Moon,
  MoreHorizontal, Mouse, MousePointerClick, Music, Music4, Navigation, Nut,
  Package, Paintbrush, Palette, Panda, PartyPopper, PawPrint, PiggyBank, Pill,
  Pizza, Plane, Plus, PlusCircle, PocketKnife, Puzzle, Rabbit, RefreshCcw, RefreshCw, Repeat, Ribbon,
  Rocket, RollerCoaster, Router, Salad, Sandwich, Save, Scale, Scissors, School,
  Search, Settings, ShieldCheck, Ship, Shirt, ShoppingBag, ShoppingBasket,
  ShoppingCart, Shovel, ShowerHead, Shrimp, Shrink, Signal, Siren, Skull,
  SlidersHorizontal, Smartphone, Sofa, Soup, Sparkles, Sprout,
  SprayCan, Square, Squirrel, Stamp, Star, Stethoscope, Store, Tablet,
  TabletSmartphone, Tag, Tags, Target, Telescope, Tent, TentTree, Theater,
  Ticket, ToggleLeft, ToggleRight, Toilet, ToyBrick, Tractor, TrainFront,
  TrainFrontTunnel, TrainTrack, TramFront, Trash2, TreePalm, Trees, TrendingDown,
  Truck, Tv, Tv2, TvMinimalPlay, Twitch, Twitter, Umbrella, University, User,
  Users, Utensils, UtensilsCrossed, Vegan, VenetianMask, Video, Videotape,
  Volleyball, Wallet, Watch, Waves, Wifi, Wine, Wrench, X, Youtube, Zap,
  Minus, ArrowLeftRight, ArrowUpDown, Camera, Upload
} from 'lucide-react';
import type { LucideProps } from 'lucide-react';
import type { FC } from 'react';

export const iconMap: { [key: string]: FC<LucideProps> } = {
  Anchor, Antenna, Apple, Armchair, AtSign, Atom, Award, Axe, Baby,
  Backpack, BaggageClaim, Banana, BarChart2, Bath, Bean, BedDouble, Beef, Beer,
  BicepsFlexed, Bike, Binoculars, Bird, Bitcoin, Bomb, Bone, Book, BookA,
  BookHeart, BookImage, BookOpen, BottleWine, Boxes, Brain, Briefcase, BrickWall,
  Brush, Bubbles, Bus, BusFront, Calendar, CalendarClock, CalendarDays, Candy,
  CandyCane, Car, CarFront, CarTaxiFront, Carrot, Cat, CheckCircle2, CheckSquare,
  ChefHat, Cherry, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, Church,
  Cigarette, Citrus, Clapperboard, Cloud, Clover, Coffee, Coins, Cookie,
  CreditCard, Croissant, Crown, CupSoda, Dice6, Dog, Donut, DownloadCloud,
  Dribbble, Drill, Droplet, Droplets, Drum, Dumbbell, Ear, Edit, Expand, Eye,
  EyeClosed, EyeOff, Feather, FerrisWheel, FileText, Film, Fish, Filter, Flame,
  Flashlight, FlaskConical, FlaskRound, Fuel, Gamepad2, Gauge, Gem, Ghost, Gift,
  GlassWater, Glasses, Globe, GraduationCap, GripVertical, Hammer, HandCoins,
  HandHeart, HandMetal, HardHat, Hash, HatGlasses, Headphones, HeartHandshake,
  HeartPulse, History, Home, Hospital, IceCream, IceCream2, IceCreamBowl, Info,
  Kayak, KeyRound, Lamp, Landmark, LayoutDashboard, LayoutGrid, Leaf, Lightbulb,
  Link, List, Loader2, LogIn, LogOut, Lollipop, Luggage, MicVocal, Milk, Moon,
  MoreHorizontal, Mouse, MousePointerClick, Music, Music4, Navigation, Nut,
  Package, Paintbrush, Palette, Panda, PartyPopper, PawPrint, PiggyBank, Pill,
  Pizza, Plane, Plus, PlusCircle, PocketKnife, Puzzle, Rabbit, RefreshCcw, RefreshCw, Repeat, Ribbon,
  Rocket, RollerCoaster, Router, Salad, Sandwich, Save, Scale, Scissors, School,
  Search, Settings, ShieldCheck, Ship, Shirt, ShoppingBag, ShoppingBasket,
  ShoppingCart, Shovel, ShowerHead, Shrimp, Shrink, Signal, Siren, Skull,
  SlidersHorizontal, Smartphone, Sofa, Soup, Sparkles, Sprout,
  SprayCan, Square, Squirrel, Stamp, Star, Stethoscope, Store, Tablet,
  TabletSmartphone, Tag, Tags, Target, Telescope, Tent, TentTree, Theater,
  Ticket, ToggleLeft, ToggleRight, Toilet, ToyBrick, Tractor, TrainFront,
  TrainFrontTunnel, TrainTrack, TramFront, Trash2, TreePalm, Trees, TrendingDown,
  Truck, Tv, Tv2, TvMinimalPlay, Twitch, Twitter, Umbrella, University, User,
  Users, Utensils, UtensilsCrossed, Vegan, VenetianMask, Video, Videotape,
  Volleyball, Wallet, Watch, Waves, Wifi, Wine, Wrench, X, Youtube, Zap,
  Minus, ArrowLeftRight, ArrowUpDown, Camera, Upload
};

export {
  Anchor, Antenna, Apple, Armchair, AtSign, Atom, Award, Axe, Baby,
  Backpack, BaggageClaim, Banana, BarChart2, Bath, Bean, BedDouble, Beef, Beer,
  BicepsFlexed, Bike, Binoculars, Bird, Bitcoin, Bomb, Bone, Book, BookA,
  BookHeart, BookImage, BookOpen, BottleWine, Boxes, Brain, Briefcase, BrickWall,
  Brush, Bubbles, Bus, BusFront, Calendar, CalendarClock, CalendarDays, Candy,
  CandyCane, Car, CarFront, CarTaxiFront, Carrot, Cat, CheckCircle2, CheckSquare,
  ChefHat, Cherry, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, Church,
  Cigarette, Citrus, Clapperboard, Cloud, Clover, Coffee, Coins, Cookie,
  CreditCard, Croissant, Crown, CupSoda, Dice6, Dog, Donut, DownloadCloud,
  Dribbble, Drill, Droplet, Droplets, Drum, Dumbbell, Ear, Edit, Expand, Eye,
  EyeClosed, EyeOff, Feather, FerrisWheel, FileText, Film, Fish, Filter, Flame,
  Flashlight, FlaskConical, FlaskRound, Fuel, Gamepad2, Gauge, Gem, Ghost, Gift,
  GlassWater, Glasses, Globe, GraduationCap, GripVertical, Hammer, HandCoins,
  HandHeart, HandMetal, HardHat, Hash, HatGlasses, Headphones, HeartHandshake,
  HeartPulse, History, Home, Hospital, IceCream, IceCream2, IceCreamBowl, Info,
  Kayak, KeyRound, Lamp, Landmark, LayoutDashboard, LayoutGrid, Leaf, Lightbulb,
  Link, List, Loader2, LogIn, LogOut, Lollipop, Luggage, MicVocal, Milk, Moon,
  MoreHorizontal, Mouse, MousePointerClick, Music, Music4, Navigation, Nut,
  Package, Paintbrush, Palette, Panda, PartyPopper, PawPrint, PiggyBank, Pill,
  Pizza, Plane, Plus, PlusCircle, PocketKnife, Puzzle, Rabbit, RefreshCcw, RefreshCw, Repeat, Ribbon,
  Rocket, RollerCoaster, Router, Salad, Sandwich, Save, Scale, Scissors, School,
  Search, Settings, ShieldCheck, Ship, Shirt, ShoppingBag, ShoppingBasket,
  ShoppingCart, Shovel, ShowerHead, Shrimp, Shrink, Signal, Siren, Skull,
  SlidersHorizontal, Smartphone, Sofa, Soup, Sparkles, Sprout, SprayCan,
  Square, Squirrel, Stamp, Star, Stethoscope, Store, Tablet, TabletSmartphone,
  Tag, Tags, Target, Telescope, Tent, TentTree, Theater, Ticket, ToggleLeft,
  ToggleRight, Toilet, ToyBrick, Tractor, TrainFront, TrainFrontTunnel, TrainTrack,
  TramFront, Trash2, TreePalm, Trees, TrendingDown, Truck, Tv, Tv2, TvMinimalPlay,
  Twitch, Twitter, Umbrella, University, User, Users, Utensils, UtensilsCrossed,
  Vegan, VenetianMask, Video, Videotape, Volleyball, Wallet, Watch, Waves, Wifi,
  Wine, Wrench, X, Youtube, Zap,
  Minus, ArrowLeftRight, ArrowUpDown, Camera, Upload
};

/** Fallback liefert ein valides Icon, wenn key unbekannt. */
export const getIconComponent = (iconName?: string): FC<LucideProps> => {
  if (iconName && iconMap[iconName]) return iconMap[iconName];
  return MoreHorizontal;
};